name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  test:
    env:
      CI: true

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - run: npm ci
  build:
    needs: test
    env:
      CI: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build --if-present

      - name: Copy build folder content to remote by ssh
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          privateKey: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          local: 'build'
          remote: 'mirestaurante/frontend/'
          rmRemote: true
